name: Build Worker Desktop Application

on:
  workflow_call:
    inputs:
      release:
        required: true
        type: boolean
    secrets:
      repo_token:
        required: true
      src_token:
        required: true

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: karya-inc/karya-server
          token: ${{ secrets.src_token }}
          ref: "v5-dev"

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version-file: "./server/.nvmrc"
          cache: "npm"
          cache-dependency-path: "**/*/package-lock.json"

      - name: Bootstrap monolith
        working-directory: ./server
        run: npm ci

      - name: Build monolith
        working-directory: ./server
        run: npx lerna run build

      - name: Bootstrap Application
        working-directory: ./server/worker-web
        run: npm ci

      - name: Build Application
        working-directory: ./server/worker-web
        run: npm run build

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.repo_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ inputs.release }}

          package_root: "./server/worker-web/"
